config/routes.rb
Rails.application.routes.draw do
  
  root 'home#top'
  get "about" => "home#about"
  # get "/:id/login_top" => "home#login_top"
  
  get "signup" => "users#new"
  post "users/create" => "users#create"
  get "login" => "users#login_form"
  post "login" => "users#login"
  post "logout" => "users#logout"
  get "users/:id" => "users#show"
  
  post "histories/:id" => "histories#update"
  resources :histories
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cloth.rb
class Cloth < ApplicationRecord
  has_many :history_details
  has_many :histories, through: :history_details
  accepts_nested_attributes_for :history_details
    
end

app/models/history.rb
class History < ApplicationRecord
  has_many :history_details
  has_many :cloths, through: :history_details
  accepts_nested_attributes_for :history_details
    
end

app/models/history_detail.rb
class HistoryDetail < ApplicationRecord
  belongs_to :history
  belongs_to :cloth
    
end

app/models/user.rb
class User < ApplicationRecord
    
    # has_secure_password

    validates :email, {presence: true, uniqueness: true}
    validates :nickname, {presence: true, uniqueness: true}
    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    
    def set_current_user
        @current_user = User.find_by(id: session[:user_id])
    end
    
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
    
#   def index
#     @histories = History.find_by(user_id: @current_user.id)
#   end
  
#   最近の投稿を表示する方法考え中。どのようにログインユーザーの投稿を表示するか。
  
  def new
   @history = History.new
   @cloth = Cloth.new
  end
  
  def create
      logger.debug("----------params=#{params[:situation]}")
      logger.debug("----------params=#{params[:brand]}")
      logger.debug("----------params=#{params[:brand_bottom]}")
      
     @his_save_success_flag = 1
    
    if params[:main_image]
     @history = History.new(
        wore_data: params[:wore_data], situation: params[:situation], memo: params[:memo], user_id: @current_user.id)
     if @history.save
        @history = History.last
        @history.main_image = "#{@history.id}.jpg"
      if @history.save
        image= params[:main_image]
        File.binwrite("public/history_images/#{@history.id}.jpg", image.read)
      @his_save_success_flag = 2
      end
     end
     
     if @his_save_success_flag == 2
         
       @cloth = Cloth.new(
         category: params[:category], brand: params[:brand], size: params[:size], color: params[:color] )
       if @cloth.save
          @history = History.last
          @cloth = Cloth.last
          @history_detail = HistoryDetail.new(
              history_id: @history.id, cloth_id: @cloth.id)
        if@history_detail.save
         @his_save_success_flag = 3
        end
       end
     end
       
     if @his_save_success_flag == 3
        @cloth_bottom = Cloth.new(
        category: params[:category_bottom], brand: params[:brand_bottom], size: params[:size_bottom], color: params[:color_bottom])
      if @cloth_bottom.save
         @history = History.last
         @cloth = Cloth.last
         @history_detail = HistoryDetail.new(
              history_id: @history.id, cloth_id: @cloth.id)
        if @history_detail.save
          redirect_to("/histories/#{@current_user.id}") 
        end
      end
     end
    end
  end
  
  def show
    @histories = History.where(user_id: params[:id]).order(created_at: :desc)
  end 
  
  def edit
      @history = History.find(params[:id])
      @history_details = HistoryDetail.where(history_id: params[:id])
      
    #   @history_details.each do |history_detail|
    #   @cloth = Cloth.where(id: history_detail.cloth_id )
    #  end
     
  end
  
  def update
     logger.debug("----------params=#{params[:id]}")
     
     
     @history = History.find(params[:id])
     @history.wore_data = params[:wore_data]
     @history.situation = params[:situation]
     @history.memo = params[:memo]
     
    if @history.save
     @history_details = HistoryDetail.where(history_id: params[:id])
     @history_details.each do |history_detail|
      cloth = Cloth.find(history_detail.cloth_id)
      cloth.category = params[:category][cloth.id.to_s]
      cloth.brand = params[:brand][cloth.id.to_s]
      cloth.size = params[:size][cloth.id.to_s]
      cloth.color = params[:color][cloth.id.to_s]
      
      logger.debug("----------cloth.id = #{cloth.id}")
     logger.debug("----------category = #{params[:category][cloth.id.to_s]}")
     
     
      
     end
    end
  end
  
  def destroy
    @history = History.find(params[:id])
    @history.destroy
    flash[:notice] = "Delete History Log"
    redirect_to("/histories/#{@current_user.id}")
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(
      email: params[:email], password: params[:password], nickname: params[:nickname], gender: params[:gender], tall: params[:tall], weight: params[:weight])
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "ユーザー登録が完了しました"
      redirect_to("/histories/#{@user.id}")
    else
      render("users/new")
    end
  end
  
  def login_form
  end
  
  def login
  @user = User.find_by(email: params[:email], password: params[:password])
    if @user
      # @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to("/histories/#{@user.id}") 
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      @email = params[:email]
      @password = params[:password]
      render("users/login_form")
    end
  end
  
  def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to("/login")
  end
  
  def show
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/histories/edit.html.erb
<div class = "history_main">
<%= form_tag("/histories/#{@history.id}", method: :patch, multipart: true) do %>
        <p>Date
        <input name="wore_data" type="date", value = <%= @history.wore_data %>></p>
        <p>Image
        <input name="main_image" type="file" ></p>
        <p>Situation
        <input name="situation" type="text", value = <%= @history.situation %>></p>
        <p>Memo<br>
        <textarea rows="10" cols="60", name="memo" ><%= @history.memo %></textarea></p>

   <% @history_details.each do |history_detail| %>
   <% cloth = Cloth.find(history_detail.cloth_id) %>
     <div class = "history_item">
          <p>Item</p>
           <p>Category
            <% if cloth.category == "s" || cloth.category == "j" || cloth.category == "su" %>
             <%= select_tag "category", options_for_select([["選択してください", ""], ["シャツ", "s"], ["ジャケット", "j"], ["スーツ", "su"]], {:selected => cloth.category })%>
            <% else %>
             <%= select_tag "category", options_for_select([["選択してください", ""], ["パンツ", "p"], ["スカート", "sk"], ["スーツ", "su_b"]], {:selected => cloth.category })%>
            <% end %>
           </p>
         <p>Brand <input name="brand[<%= history_detail.cloth_id %>]", type="text" value= "<%= cloth.brand %>" ></p>
         <p>Size
          <%= select_tag "size[#{history_detail.cloth_id}]", options_for_select([["選択してください", ""], ["S", "S"], ["M", "M"], ["L", "L"]], {:selected => cloth.size })%>
         </p>
         <p>Color <input name="color[<%= history_detail.cloth_id %>]", type="text" value=<%= cloth.color %>></p>
     </div>
   
   <% end %>
  <input type="submit" value="Save">
 <% end %>

</div>

app/views/histories/new.html.erb
<div class = "history_main">
  <div class="container">
    <div class="form-heading"> Upload Log </div>
    <div class="form users-form">
      <div class="form-body">
        
        <%= form_tag("/histories", {multipart:true}) do %>
        <p>Date
        <input name="wore_data" type="date"></p>
        <p>Image
        <input name="main_image" type="file" ></p>
        <p>Situation
        <input name="situation" type="text" ></p>
        <p>Memo<br>
        <textarea rows="10" cols="60", name="memo">Memoを入してください</textarea></p>
        
        <p>Item</p>
        <p>Tops</p>
         <p>Category <select name = "category">
           <option value="">選択してください</option>
           <option value="s"> シャツ </option>
           <option value="j"> ジャケット </option>
           <option value="su"> スーツ </option>
         </select>
         </p>
         <p>Brand <input name="brand" type="text" ></p>
         <p>Size <select name="size">
          <option value="">選択してください</option>
          <option value="S"> S </option>
          <option value="M"> M </option>
          <option value="L"> L </option>
         </select>
         </p>
         <p>Color <input name="color" type="text" ></p>
         
         <p>Bottoms</p>
         <p>Category <select name = "category_bottom">
           <option value="">選択してください</option>
           <option value="p"> パンツ </option>
           <option value="sk"> スカート </option>
           <option value="su_b"> スーツ </option>
         </select>
         </p>
         <p>Brand <input name="brand_bottom" type="text" ></p>
         <p>Size
         <select name="size_bottom">
          <option value="">選択してください</option>
          <option value="S"> S </option>
          <option value="M"> M </option>
          <option value="L"> L </option>
         </select>
         </p>
         <p>Color <input name="color_bottom" type="text" ></p>
         
         <input type="submit" value="Next">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/histories/show.html.erb
<div class = "history_main">
<% @histories.each do |history| %>
<div class = "each_history">
<%= history.wore_data %></br>
<%= link_to image_tag("/history_images/#{history.id}.jpg", {:class => "main_image", :border => '0', :alt => 'Edit'}), edit_history_path(history.id) %></br>
</div>
<% end %>
</div>

app/views/home/about.html.erb
<div class="about-main">
  <h2>StyleLogとは</h2>
  <p>
    「今日は何を着ていこうか」
    
  </p>
  <img class="about-img" src="/tweets.png">
</div>

app/views/home/top.html.erb
<div class = "top-main">
 <div class = "top-message">
<h1> 
 Record</br>
 your</br>
 style</br>
</h1>
</div>
<p> 日々の着こなしを記録する</p>
<img class="top-img" src="/top.jpg">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StyleLog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    
  </head>
  <header>
  <div class="header-logo">
     <%= link_to("Style Log", "/") %>
  </div>
  <ul class="header-menus">
   <% if @current_user %>
     <li>
      <%= link_to(@current_user.nickname, "/histories/#{@current_user.id}") %>
     </li>
     <li>
       <%=link_to("Add Log", new_history_path) %>
     </li>
     <li>
      <%=link_to("Situation", "/") %>
     </li>
     <li>
      <%=link_to("Season", "/") %>
     </li>
     <li>
      <%=link_to("Log out", "/logout", method: :post) %>
     </li>
  
   <% else %> 

     <li>
      <%=link_to("ABOUT", "/about") %>
     </li>
     <li>
      <%=link_to("Sing up", "/signup") %>
     </li>
     <li>
      <%=link_to("Log in", "/login") %>
     </li>

   <% end %>
     
  </ul>
 </header>

    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/login_form.html.erb
<div class="main_users_new">
  <div class="container">
    <div class="form-heading"> Login</div>
    <% if @error_message %>
     <div class="form-error">
      <%= @error_message %>
     </div>
    <% end %>
    <%= form_tag("/login") do %>
    <div class="form users-form">
      <div class="form-body">
        <p>Mail Address</p>
        <input name="email" value="<%= @email %>">
        <p>Password</p>
        <input type="password" name="password" value="<%= @password %>">
        <input type="submit" value="Login">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="main_users_new">
  <div class="container">
    <div class="form-heading">新規ユーザー登録</div>
    <div class="form users-form">
      <div class="form-body">
         <% @user.errors.full_messages.each do |message| %>
         <div class="form-error">
           <%= message %>
          </div>
        <% end %>
        <%= form_tag("/users/create") do %>
        <p>Mail Adress</p>
        <input name="email" value="<%= @user.email %>">
        <p>Password</p>
        <input name="password" type="password" value="<%= @user.password %>">
        <p>Nickname</p>
        <input name="nickname" value="<%= @user.nickname %>">
        <p>Gender</p>
        <select name= "gender" value="<%= @user.gender %>">
         <option value="">選択してください</option>
         <option value="1"> Male </option>
         <option value="2"> Female </option>
        </select>
        <p>Height (cm)</p>
        <input name="tall" value="<%= @user.tall %>">
        <p>Weight (kg)</p>
        <input name="weight" value="<%= @user.weight %>">
        <input type="submit" value="Make your account">
        <% end %>
      </div>
    </div>
  </div>
</div>